import os
import glob
import configparser
import subprocess
import sqlite3
from datetime import datetime


_known_procs = {} # Stores process state between polls: { pid: (comm, cmdline) }

def get_new_processes():
	"""    
	Scans /proc and returns a list of new processes since the last call,
	or None if there are no new ones.

	Each entry in the list is a dict:
		{ "pid": "1234", "comm": "soffice", "cmdline": ["soffice", "--writer"] }
		
	Generated by Claude 
	"""
	current_procs = {}

	for entry in os.listdir("/proc"):
		if not entry.isdigit():
			continue
		pid = entry
		try:
			with open(f"/proc/{pid}/comm") as f:
				comm = f.read().strip()
			with open(f"/proc/{pid}/cmdline", "rb") as f:
				# cmdline args are null-byte separated
				parts = f.read().split(b"\x00")
				cmdline = [p.decode(errors="replace") for p in parts if p]
		except (FileNotFoundError, PermissionError):
			# Process may have exited between the listdir and the read
			continue

		current_procs[pid] = (comm, cmdline)

	new_procs = []
	for pid, (comm, cmdline) in current_procs.items():
		if pid not in _known_procs:
			new_procs.append({"pid": pid, "comm": comm, "cmdline": cmdline})

	_known_procs.clear()
	_known_procs.update(current_procs)

	# return new_procs if new_procs else None
	return (new_procs if new_procs else None, set(current_procs.keys()))



# Maps .desktop Exec= binary names to the actual comm name seen in /proc
_BINARY_ALIASES = {
	"libreoffice":         "soffice",
	"libreoffice-writer":  "soffice",
	"libreoffice-calc":    "soffice",
	"libreoffice-impress": "soffice",
	"libreoffice-draw":    "soffice",
}

def load_desktop_files(desktop_app_dirs):
	"""
	Parses .desktop files and returns a dict mapping known executable/comm
	names to their friendly app names.

	e.g. {
		"firefox":          "Firefox Web Browser",
		"soffice":          "LibreOffice",
		"soffice --writer": "LibreOffice Writer",
	}
	"""
	apps = {}
	current_desktop = get_current_desktop()

	for directory in desktop_app_dirs:
		for filepath in glob.glob(os.path.join(directory, "*.desktop")):
			try:
				cp = configparser.ConfigParser(interpolation=None, strict=False)
				cp.read(filepath, encoding="utf-8")

				if not cp.has_section("Desktop Entry"):
					continue

				entry = cp["Desktop Entry"]

				if entry.get("Type", "") != "Application":
					continue
				if entry.get("NoDisplay", "false").lower() == "true":
					continue

				if current_desktop:
					only_show_in = entry.get("OnlyShowIn", "")
					if only_show_in and current_desktop not in only_show_in.split(";"):
						continue

					not_show_in = entry.get("NotShowIn", "")
					if current_desktop in not_show_in.split(";"):
						continue

				name = entry.get("Name", "").strip()
				exec_line = entry.get("Exec", "").strip()

				if not name or not exec_line:
					continue

				# Strip field codes (%u, %F, etc.)
				tokens = [t for t in exec_line.split() if not t.startswith("%")]
				if not tokens:
					continue

				binary = os.path.basename(tokens[0])

				# For Flatpak apps, the real command is in --command=<name>
				if binary == "flatpak":
					command_arg = next((t for t in tokens if t.startswith("--command=")), None)
					if command_arg:
						binary = command_arg.split("=", 1)[1]
					else:
						continue

				# Normalise known wrapper binaries to the real comm name
				binary = _BINARY_ALIASES.get(binary, binary)

				# Primary key: just the executable name
				apps.setdefault(binary, name)

				# Truncated key: handles kernel's 15-char comm limit in /proc/comm
				if len(binary) > 15:
					apps.setdefault(binary[:15], name)

				# Suite key: executable + first flag, for apps like LibreOffice
				flags = [t for t in tokens[1:] if t.startswith("--")]
				if flags:
					apps.setdefault(f"{binary} {flags[0]}", name)

			except Exception:
				continue

	return apps


def get_flatpak_desktop_dirs():
	"""
	Asks flatpak for all configured installation paths and returns the
	exports/share/applications subdirectory for each one that exists.
	Returns an empty list if flatpak is not installed.
	"""
	dirs = []
	try:
		result = subprocess.run(
			["flatpak", "--installations"],
			capture_output=True, text=True, timeout=5
		)
		for line in result.stdout.splitlines():
			base = line.strip()
			candidate = os.path.join(base, "exports", "share", "applications")
			if os.path.isdir(candidate):
				dirs.append(candidate)
	except FileNotFoundError:
		pass  # flatpak not installed
	return dirs


def get_current_desktop():
	"""
	Returns the current desktop environment as reported by XDG_CURRENT_DESKTOP,
	e.g. "GNOME", "KDE", "XFCE".
	Returns None if not set.
	"""
	desktop = os.environ.get("XDG_CURRENT_DESKTOP", "")
	# XDG_CURRENT_DESKTOP can be colon-separated e.g. "ubuntu:GNOME"
	return desktop.split(":")[0] if desktop else None



def OLDfilter_to_desktop_apps(procs, desktop_files):
	"""
	Filters a list of new processes down to those matching a known
	desktop menu application.

	Returns a list of dicts:
		{ "pid": "1234", "comm": "soffice", "cmdline": [...], "app_name": "LibreOffice Writer" }
	Or None if no matches.
	"""
	matches = []

	if procs is None:
		return None

	for proc in procs:
		comm = proc["comm"]
		cmdline = proc["cmdline"]

		# Skip apps pre-loaded silently by GNOME in the background
		# if "--gapplication-service" in cmdline:
		#     continue

		# Skip GNOME search provider helper processes
		# if any("search-provider" in arg for arg in cmdline):
		#     continue

		# Skip system helper processes
		if any(arg.startswith("/usr/libexec/") for arg in cmdline):
			continue

		# Find the first -- flag in cmdline (skipping the binary at index 0)
		first_flag = next((a for a in cmdline[1:] if a.startswith("--")), None)

		# Try "comm --flag" first, then fall back to just "comm"
		app_name = None
		if first_flag:
			app_name = desktop_files.get(f"{comm} {first_flag}")
		if not app_name:
			app_name = desktop_files.get(comm)

		if app_name:
			matches.append({**proc, "app_name": app_name})

	return matches if matches else None



_candidate_apps = {}

def filter_to_desktop_apps(procs, running_pids, desktop_files):
	global _candidate_apps

	# Confirm candidates from last poll that are still running
	confirmed = []
	for pid, app_dict in _candidate_apps.items():
		if pid in running_pids:
			confirmed.append(app_dict)

	# Build new candidates from this poll
	new_candidates = {}
	if procs:
		for proc in procs:
			comm = proc["comm"]
			cmdline = proc["cmdline"]

			if any(arg.startswith("/usr/libexec/") for arg in cmdline):
				continue

			first_flag = next((a for a in cmdline[1:] if a.startswith("--")), None)

			app_name = None
			if first_flag:
				app_name = desktop_files.get(f"{comm} {first_flag}")
			if not app_name:
				app_name = desktop_files.get(comm)

			if app_name:
				new_candidates[proc["pid"]] = {**proc, "app_name": app_name}

	_candidate_apps = new_candidates
	return confirmed if confirmed else None


###
# Database stuff
###

def init_db(db_path):
	"""
	Creates the database and table if they don't already exist.
	Returns a connection object.

	Fields
		date        -- YYYY-MM-DD
		launched_at -- ISO-8601 timestamp
		app_name    -- friendly name (from .desktop file)
		executable  -- process comm name
	"""
	os.makedirs(os.path.dirname(db_path), exist_ok=True)
	conn = sqlite3.connect(db_path)
	conn.execute("""
		CREATE TABLE IF NOT EXISTS app_launches (
			id          INTEGER PRIMARY KEY AUTOINCREMENT,
			date        TEXT    NOT NULL,
			app_name    TEXT    NOT NULL,
			comm        TEXT    NOT NULL,
			pid         TEXT    NOT NULL,
			cmdline     TEXT    NOT NULL
		)
	""")
	conn.execute("""
		CREATE UNIQUE INDEX IF NOT EXISTS idx_date_app
		ON app_launches(date, app_name)
	""")
	conn.commit()
	return conn


def log_launch(conn, app):
	"""
	Records an app launch if it hasn't already been recorded today.
	The unique index on (date, app_name) means duplicate inserts are silently ignored.
	"""
	date = datetime.now().strftime("%Y-%m-%d")
	conn.execute("""
		INSERT OR IGNORE INTO app_launches (date, app_name, comm, pid, cmdline)
		VALUES (?, ?, ?, ?, ?)
	""", (
		date,
		app["app_name"],
		app["comm"],
		app["pid"],
		" ".join(app["cmdline"]),
	))
	conn.commit()