import os
import datetime

_known_procs = {} # Stores process state between polls: { pid: (comm, cmdline) }
_current_day = datetime.date.today()

def get_new_processes():
	"""    
	Scans /proc and returns a list of new processes since the last call,
	or None if there are no new ones.

	Each entry in the list is a dict:
		{ "pid": "1234", "comm": "soffice", "cmdline": ["soffice", "--writer"] }
		
	Generated by Claude 
	"""
	current_procs = {}

	# if the date has changed, start a fresh dictionary of _known_procs
	if _current_day != datetime.date.today():
		_known_procs.clear()

	for entry in os.listdir("/proc"):
		if not entry.isdigit():
			continue
		pid = entry
		try:
			with open(f"/proc/{pid}/comm") as f:
				comm = f.read().strip()
			with open(f"/proc/{pid}/cmdline", "rb") as f:
				# cmdline args are null-byte separated
				parts = f.read().split(b"\x00")
				cmdline = [p.decode(errors="replace") for p in parts if p]
		except (FileNotFoundError, PermissionError):
			# Process may have exited between the listdir and the read
			continue

		current_procs[pid] = (comm, cmdline)

	new_procs = []
	for pid, (comm, cmdline) in current_procs.items():
		if pid not in _known_procs:
			new_procs.append({"pid": pid, "comm": comm, "cmdline": cmdline})

	_known_procs.clear()
	_known_procs.update(current_procs)

	# return 
	# 1) new_procs or None
	# 2) a set of current_procs keys
	return (new_procs if new_procs else None, set(current_procs.keys()))



_candidate_apps = {}

def filter_to_desktop_apps(procs, running_pids, desktop_files):

	# Confirm candidates from last poll that are still running
	confirmed = []
	for pid, app_dict in _candidate_apps.items():
		if pid in running_pids:
			confirmed.append(app_dict)

	# Build new candidates from this poll
	new_candidates = {}
	if procs:
		for proc in procs:
			comm = proc["comm"]
			cmdline = proc["cmdline"]

			if any(arg.startswith("/usr/libexec/") for arg in cmdline):
				continue

			first_flag = next((a for a in cmdline[1:] if a.startswith("--")), None)

			app_name = None
			if first_flag:
				app_name = desktop_files.get(f"{comm} {first_flag}")
			if not app_name:
				app_name = desktop_files.get(comm)

			if app_name:
				new_candidates[proc["pid"]] = {**proc, "app_name": app_name}

	_candidate_apps.clear()
	_candidate_apps.update(new_candidates)
	return confirmed if confirmed else None
